--- #YAML:1.0
name: Mail-Action-Role-Purge
version: 0.10
license: perl
distribution_type: module
requires:
  Class::Roles: 0.30
  Mail::Action: 0.20
  Mail::SimpleList: 0.85
  Mail::TempAddress: 0.55
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Mail::Action::Role::Purge:
    file: lib/Mail/Action/Role/Purge.pm
    version: 0.01
generated_by: Module::Build version 0.21
